name: auto-format

on:
  pull_request: null
  
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v4
      - name: Run prettier
        run: npx prettier --write .
      - uses: tj-actions/verify-changed-files@v17
        id: verify-changed-files
        with:
          fail-if-changed: 'true'
          fail-message: 'Run linter before commit!'
