name: auto-format
on:
    pull_request:
    push:
        branches:
            - master
            - dev
jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
              with:
                  ref: ${{ github.head_ref }}
            - name: prettier
              run: npx prettier --write .
            - name: Check for modified files
              id: git-check
              run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
            - name: Push changes
              if: steps.git-check.outputs.modified == 'true'
              run: |
                  git config --global user.name 'Peter Evans'
                  git config --global user.email 'peter-evans@users.noreply.github.com'
                  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
                  git commit -am "Automated changes"
                  git push
